In [1]:
import pandas as pd

In [2]:
pd.__file__

'/Users/ginadurante/Documents/GitHub/data-engineering-zoomcamp/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [ ]:
# Read in data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + 'yellow_tripdata_2021-01.csv.gz')

In [ ]:
# Display first rows
df.head()

In [ ]:
# Check data types
df.dtypes

In [ ]:
# Check data shape
df.shape

In [ ]:
len(df)

In [ ]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates
)

In [ ]:
df.dtypes

In [ ]:
df

In [ ]:
!uv add psycopg2-binary

In [3]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [ ]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

In [ ]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

In [ ]:
df_iter = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [ ]:
# for df_chunk in df_iter:
    # print(len(df_chunk))

In [ ]:
!uv add tqdm

In [ ]:
# df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

In [4]:
from tqdm.auto import tqdm

In [ ]:
first = True

for df_chunk in tqdm(df_iter):

    if first:
        # Create table schema (no data)
        df_chunk.head(0).to_sql(
            name="yellow_taxi_data",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="yellow_taxi_data",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

In [ ]:
# Read in green data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/'
df = pd.read_csv(prefix + 'green_tripdata_2021-01.csv.gz')

In [ ]:
df.head()

In [ ]:
# Check data types
df.dtypes

In [ ]:
# Check data shape
df.shape

In [ ]:
len(df)

In [ ]:
dtype = {
    "VendorID": "Int64",
    "store_and_fwd_flag": "string",
    "RatecodeID": "Int64",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "payment_type": "Int64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'green_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates
)

In [ ]:
df.dtypes

In [ ]:
df

In [ ]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

In [ ]:
df_iter = pd.read_csv(
    prefix + 'green_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=50000
)

In [ ]:
for df_chunk in df_iter:
    print(len(df_chunk))

In [ ]:
first = True

for df_chunk in tqdm(df_iter):

    if first:
        # Create table schema (no data)
        df_chunk.head(0).to_sql(
            name="green_taxi_data",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="green_taxi_data",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

In [ ]:
# Need to import green trip data for 2025-11

In [ ]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

In [ ]:
# df = pd.read_parquet('green_tripdata_2025-11.parquet')

In [ ]:
# df.to_csv('green_tripdata_2025-11.csv', index=False)

In [5]:
!pwd

/Users/ginadurante/Documents/GitHub/data-engineering-zoomcamp/pipeline

In [6]:
df = pd.read_csv("green_tripdata_2025_11.csv")

In [7]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46907,2,2025-11-30 19:58:34,2025-11-30 20:14:28,NaN,NaN,59,51,NaN,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,NaN,NaN,NaN,0.00
46908,2,2025-11-30 19:34:00,2025-11-30 19:46:00,NaN,NaN,74,151,NaN,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,NaN,NaN,NaN,0.00
46909,2,2025-11-30 21:46:46,2025-11-30 22:17:55,NaN,NaN,33,163,NaN,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,NaN,NaN,NaN,0.75
46910,2,2025-11-30 21:00:00,2025-11-30 21:15:00,NaN,NaN,16,95,NaN,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,NaN,NaN,NaN,0.00
46911,2,2025-11-30 23:26:00,2025-11-30 23:42:00,NaN,NaN,65,87,NaN,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,NaN,NaN,NaN,0.75

In [8]:
# Check data types
df.dtypes

VendorID                   int64
lpep_pickup_datetime         str
lpep_dropoff_datetime        str
store_and_fwd_flag           str
RatecodeID               float64
PULocationID               int64
DOLocationID               int64
passenger_count          float64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type             float64
trip_type                float64
congestion_surcharge     float64
cbd_congestion_fee       float64
dtype: object

In [9]:
dtype = {
    "VendorID": "Int64",
    "store_and_fwd_flag": "string",
    "RatecodeID": "Int64",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "payment_type": "Int64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime"
]

df = pd.read_csv(
    'green_tripdata_2025_11.csv',
    dtype=dtype,
    parse_dates=parse_dates
)

In [10]:
df.dtypes

VendorID                          Int64
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               string
RatecodeID                        Int64
PULocationID                      Int64
DOLocationID                      Int64
passenger_count                   Int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      Int64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [11]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1,166,262,1,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46907,2,2025-11-30 19:58:34,2025-11-30 20:14:28,<NA>,<NA>,59,51,<NA>,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,<NA>,NaN,NaN,0.00
46908,2,2025-11-30 19:34:00,2025-11-30 19:46:00,<NA>,<NA>,74,151,<NA>,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,<NA>,NaN,NaN,0.00
46909,2,2025-11-30 21:46:46,2025-11-30 22:17:55,<NA>,<NA>,33,163,<NA>,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,<NA>,NaN,NaN,0.75
46910,2,2025-11-30 21:00:00,2025-11-30 21:15:00,<NA>,<NA>,16,95,<NA>,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,<NA>,NaN,NaN,0.00
46911,2,2025-11-30 23:26:00,2025-11-30 23:42:00,<NA>,<NA>,65,87,<NA>,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,<NA>,NaN,NaN,0.75

In [18]:
print(pd.io.sql.get_schema(df, name='green_tripdata_2025_11', con=engine))

CREATE TABLE green_tripdata_2025_11 (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [19]:
df.head(n=0).to_sql(name='green_tripdata_2025_11', con=engine, if_exists='replace')

0

In [20]:
df.to_sql(name='green_tripdata_2025_11', con=engine, if_exists='replace')

912